set(ENABLE_LINE_DOUBLING 1)
set(AUTOSCALE 1)

set(KEY_UP SDLK_UP)
set(KEY_DOWN SDLK_DOWN)
set(KEY_LEFT SDLK_LEFT)
set(KEY_RIGHT SDLK_RIGHT)
set(KEY_ENTER SDLK_LCTRL) # A
set(KEY_TOGGLE SDLK_LALT) # B
set(KEY_BACKSPACE SDLK_BACKSPACE) # R
set(KEY_SHIFT SDLK_TAB) # L
set(KEY_LOCATION SDLK_LSHIFT) # Y
set(KEY_ACTIVATE SDLK_SPACE) # X
set(KEY_QUIT SDLK_ESCAPE) # SELECT
set(KEY_HELP SDLK_RETURN) # START
